# Generated by Django 4.1 on 2022-10-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='typ',
            field=models.CharField(choices=[('Accreditation', 'Accreditation'), ('Appraisal', 'Appraisal'), ('Resource', 'Resource')], default='Resource', max_length=20),
        ),
    ]
