# Generated by Django 4.1 on 2022-10-18 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0002_resources_typ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources',
            old_name='typ',
            new_name='filetype',
        ),
        migrations.AddField(
            model_name='resources',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
